<#
.SYNOPSIS
  Add an account-email line to the Claude Code status line (PowerShell host).
.DESCRIPTION
  Writes a PowerShell status-line script that resolves the active account email
  from the per-account .claude.json (CLAUDE_CONFIG_DIR wins, else ~\.claude.json),
  and wires settings.json to call it. Use the PRIMARY config dir as -Target if
  settings.json is symlink-shared across accounts.
.PARAMETER Target
  Config dir whose settings.json to modify. Default: ~\.claude
.PARAMETER Mode
  auto (default) | new | print. ("inject" into an arbitrary existing script is
  not attempted on Windows — use print and merge manually.)
.EXAMPLE
  .\install-statusline.ps1
#>
param(
  [string]$Target = (Join-Path $HOME ".claude"),
  [ValidateSet("auto","new","print")][string]$Mode = "auto"
)
$ErrorActionPreference = "Stop"
$settings = Join-Path $Target "settings.json"
$hooks    = Join-Path $Target "hooks"
New-Item -ItemType Directory -Force -Path $hooks | Out-Null
$slPath   = Join-Path $hooks "statusline.ps1"

$scriptBody = @'
# Generated by claude-account-switch. Active-account email status line.
$null = $input | Out-Null
$cfg = if ($env:CLAUDE_CONFIG_DIR) { Join-Path $env:CLAUDE_CONFIG_DIR ".claude.json" } else { Join-Path $HOME ".claude.json" }
if (Test-Path $cfg) {
  try {
    $email = (Get-Content $cfg -Raw | ConvertFrom-Json).oauthAccount.emailAddress
    if ($email) {
      $tag = if ($env:CLAUDE_CONFIG_DIR -match 'work|business') { 'biz' } elseif (-not $env:CLAUDE_CONFIG_DIR) { 'personal' } else { 'alt' }
      Write-Output "[$tag] $email"
    }
  } catch {}
}
'@

$current = ""
if ((Test-Path $settings)) {
  try { $current = (Get-Content $settings -Raw | ConvertFrom-Json).statusLine.command } catch {}
}

$effective = $Mode
if ($Mode -eq "auto") { $effective = if ($current) { "print" } else { "new" } }

Write-Host "settings.json: $settings"
Write-Host "current statusLine: $((@($current),'<none>')[[int]([string]::IsNullOrEmpty($current))])"
Write-Host "mode: $effective`n"

switch ($effective) {
  "new" {
    Set-Content -Path $slPath -Value $scriptBody -Encoding UTF8
    if (-not (Test-Path $settings)) { Set-Content $settings "{}" -Encoding UTF8 }
    Copy-Item $settings "$settings.bak" -Force
    $json = Get-Content $settings -Raw | ConvertFrom-Json
    $cmd  = "pwsh -NoProfile -File `"$slPath`""
    $json | Add-Member -NotePropertyName statusLine -NotePropertyValue ([pscustomobject]@{type="command"; command=$cmd}) -Force
    $json | ConvertTo-Json -Depth 20 | Set-Content $settings -Encoding UTF8
    Write-Host "wrote $slPath and set statusLine in $settings (backup: $settings.bak)"
  }
  "print" {
    Write-Host "A status line already exists. Add an account row by emitting this first:"
    Write-Host "----------------------------------------"
    Write-Host $scriptBody
    Write-Host "----------------------------------------"
  }
}
