#!/usr/bin/env bash
# install-statusline.sh — add an account-email line to the Claude Code status
# line. Resolves the email dynamically from the active .claude.json (respects
# CLAUDE_CONFIG_DIR), so one shared script serves all accounts.
#
# Usage:
#   install-statusline.sh [--target ~/.claude] [--mode auto]
#
#   --target  Config dir whose settings.json/statusline to modify. Default: ~/.claude
#             (Use the PRIMARY dir if settings.json is symlink-shared — editing
#              the shared file covers every account.)
#   --mode    auto (default) | new | inject | print
#               new    = scaffold a fresh statusline.sh + wire settings.json
#               inject = insert account block into existing script file
#               print  = just print the snippet, change nothing
#   --help
#
# Idempotent. Backs up any file it edits.
set -euo pipefail

TARGET="$HOME/.claude"
MODE="auto"

while [ $# -gt 0 ]; do
  case "$1" in
    --target) TARGET="${2:-}"; shift 2 ;;
    --mode) MODE="${2:-}"; shift 2 ;;
    --help|-h) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
TARGET="${TARGET/#\~/$HOME}"
SETTINGS="$TARGET/settings.json"
# If settings.json is a symlink (profile dir sharing the primary's settings),
# edit the link target instead — replacing the link with a regular file would
# silently fork the shared config.
if [ -L "$SETTINGS" ]; then
  real=$(readlink "$SETTINGS")
  case "$real" in /*) ;; *) real="$(dirname "$SETTINGS")/$real" ;; esac
  echo "note: $SETTINGS is a symlink — editing its target $real to keep sharing intact"
  SETTINGS="$real"
fi
HOOKS="$TARGET/hooks"
mkdir -p "$HOOKS"

START="# >>> cc-account-switch: account line >>>"
END="# <<< cc-account-switch: account line <<<"

read -r -d '' ACCT_BLOCK <<'BLOCK' || true
# >>> cc-account-switch: account line >>>
# Active-account email as the top status line. Reads the per-account .claude.json
# (CLAUDE_CONFIG_DIR wins, else ~/.claude.json). Requires jq; degrades silently.
if command -v jq >/dev/null 2>&1; then
  if [ -n "$CLAUDE_CONFIG_DIR" ]; then _cas_json="$CLAUDE_CONFIG_DIR/.claude.json"; else _cas_json="$HOME/.claude.json"; fi
  _cas_email=$(jq -r '.oauthAccount.emailAddress // empty' "$_cas_json" 2>/dev/null)
  if [ -n "$_cas_email" ]; then
    case "$CLAUDE_CONFIG_DIR" in
      *work*|*business*) _cas_color=208; _cas_tag="biz" ;;
      "")                _cas_color=245; _cas_tag="personal" ;;
      *)                 _cas_color=39;  _cas_tag="alt" ;;
    esac
    printf '\033[38;5;%dm[%s] %s\033[0m\n' "$_cas_color" "$_cas_tag" "$_cas_email"
  fi
fi
# <<< cc-account-switch: account line <<<
BLOCK

# Determine current statusLine command, if any.
current_cmd=""
if [ -f "$SETTINGS" ] && command -v jq >/dev/null 2>&1; then
  current_cmd=$(jq -r '.statusLine.command // empty' "$SETTINGS" 2>/dev/null || true)
fi

# Extract a script-file path from the command (best effort), if it references one.
script_path=""
case "$current_cmd" in
  *.sh*) script_path=$(printf '%s\n' "$current_cmd" | grep -oE '(/|~|\$HOME)[^"'"'"' ]*\.sh' | head -1) ;;
esac
script_path="${script_path/#\~/$HOME}"
script_path="${script_path/#\$HOME/$HOME}"

resolve_mode() {
  if [ "$MODE" != "auto" ]; then echo "$MODE"; return; fi
  if [ -z "$current_cmd" ]; then echo "new"; return; fi
  if [ -n "$script_path" ] && [ -f "$script_path" ]; then echo "inject"; return; fi
  echo "print"
}
EFFECTIVE=$(resolve_mode)
echo "settings.json: $SETTINGS"
echo "current statusLine: ${current_cmd:-<none>}"
echo "mode: $EFFECTIVE"
echo

case "$EFFECTIVE" in
  new)
    SL="$HOOKS/statusline.sh"
    {
      echo '#!/usr/bin/env bash'
      echo '# Generated by cc-account-switch. Account email + (add your own segments below).'
      echo 'INPUT=$(cat)'
      echo ''
      printf '%s\n' "$ACCT_BLOCK"
    } > "$SL"
    chmod +x "$SL"
    # Wire settings.json.
    if command -v jq >/dev/null 2>&1; then
      [ -f "$SETTINGS" ] || echo '{}' > "$SETTINGS"
      cp "$SETTINGS" "$SETTINGS.bak"
      tmp=$(mktemp)
      jq --arg cmd "bash \"$SL\"" '.statusLine = {type:"command", command:$cmd}' "$SETTINGS" > "$tmp" && mv "$tmp" "$SETTINGS"
      echo "wrote $SL and set statusLine in $SETTINGS (backup: $SETTINGS.bak)"
    else
      echo "wrote $SL — but jq missing, so set this in $SETTINGS manually:"
      echo "  \"statusLine\": { \"type\": \"command\", \"command\": \"bash \\\"$SL\\\"\" }"
    fi
    ;;

  inject)
    if grep -qF "$START" "$script_path"; then
      echo "account line already present in $script_path — nothing to do."
      exit 0
    fi
    cp "$script_path" "$script_path.bak"
    tmp=$(mktemp); blockfile=$(mktemp)
    printf '\n%s\n' "$ACCT_BLOCK" > "$blockfile"
    # Splice via head/tail (portable; BSD awk rejects multiline -v values).
    # Insert after the first 'INPUT=$(cat)' line if present, else after shebang (line 1).
    ln=$(grep -nE '^INPUT=\$\(cat\)' "$script_path" | head -1 | cut -d: -f1)
    [ -n "$ln" ] || ln=1
    head -n "$ln" "$script_path" > "$tmp"
    cat "$blockfile" >> "$tmp"
    tail -n +"$((ln+1))" "$script_path" >> "$tmp"
    mv "$tmp" "$script_path"
    rm -f "$blockfile"
    echo "injected account line after line $ln of $script_path (backup: $script_path.bak)"
    ;;

  print)
    echo "Could not safely auto-edit (inline command or script not found)."
    echo "Add this near the TOP of your status-line script (after it reads stdin):"
    echo "----------------------------------------"
    printf '%s\n' "$ACCT_BLOCK"
    echo "----------------------------------------"
    ;;
  *) echo "error: unknown mode '$EFFECTIVE'" >&2; exit 2 ;;
esac
